### ISSUE TITLE
Issues pack #1

### ISSUE THREAD

**Issue by EgrOnWire** [Metastruct/meta-mapfiles#2]
**Ugly books in the bookshop. Meta has better version.**

![gm_construct_m3_910001](https://cloud.githubusercontent.com/assets/10175546/19093137/95f31606-8a92-11e6-9233-4c7d139167e8.jpg)

**trigger_hurt in the core area bugged out and killing randomly.**

![gm_construct_m3_910003](https://cloud.githubusercontent.com/assets/10175546/19093161/ad9e924e-8a92-11e6-8147-c2ee0d8c8eab.jpg)

**Bad collisions in the richroom (you can get stuck in this)**
![gm_construct_m3_910003](https://cloud.githubusercontent.com/assets/10175546/19093184/c9554a32-8a92-11e6-9b1f-063409fde5fe.jpg)

**Wierd lighting scheme on minigame area entrance.**
![gm_construct_m3_910004](https://cloud.githubusercontent.com/assets/10175546/19093206/e355e95a-8a92-11e6-928b-a4e2853b33e7.jpg)

**Misplaced props in the theatre.**
![gm_construct_m3_910005](https://cloud.githubusercontent.com/assets/10175546/19093227/f293dbf2-8a92-11e6-94f1-e16c396b4971.jpg)

**Comment by EgrOnWire** [comment]
-13868 -141 13099 - Nodraw required (textures not visible)

**Comment by EgrOnWire** [comment]
-12832.424804688, 731.46130371094, 14228.956054688 - Very brush intemsive (we do care about limits, dont we)?

**Comment by EgrOnWire** [comment]
-12686.065429688, -597.89270019531, 13048.037109375 Lava textures gone fucks

**Comment by KabusIblis** [comment]
majority of these were fixed, closing
