### ISSUE TITLE
prop issues - m3

### ISSUE THREAD

**Issue by KabusDev** [Metastruct/meta-mapfiles#4]
http://i.imgur.com/XTFJn8i.jpg
-9713.968750 907.805725 14399.031250

**Comment by Immortalyes** [comment]
ugly trees on roof glass, better to remove
http://i.imgur.com/WyMMt2l.jpg
-10711.113281 -2685.828857 14168.231445

no collision on fridge
http://i.imgur.com/ordANHu.jpg
-12155.831055 2295.960938 14027.231445

http://i.imgur.com/4mWqFF0.jpg
-11191.095703 -2681.903076 14168.231445

**Comment by KabusDev** [comment]
http://i.imgur.com/3iRwjUU.jpg
bunker issue with pipes being full bright

**Comment by KabusDev** [comment]
fixed in recent svn commit, giggle was notified about bunker issue
