### ISSUE TITLE
Laser off center

### ISSUE THREAD

**Issue by ghost** [Metastruct/meta-mapfiles#5]
**Quite OCDery.**
This has been a problem for a long time I know.
http://i.imgur.com/RIaVoIl.jpg

Laser hydro machinery position: -7872,2728,-15720
Lasers position: -7867.406250 2966.312500 -15722.593750.

http://i.imgur.com/AACk4BE.jpg is not connected right, why not just scale the laser...
Also, there washing machine tubes attached to only one side of it.

Der fuhrer will be mad about this.

**Comment by elijah-h-lgtm** [comment]
I never noticed this til now. I hate you.

**Comment by KabusDev** [comment]
the laser is controlled by lua as far as I'm aware and I cant touch much of the lua nor do I really want to
@Python1320 want to fix this?

**Comment by KabusDev** [comment]
fixed
